Added arm vision packages
RoBorregos/Robocup-Home pull request #35
Opened 2020-04-28 19:08 UTC by IquiBalamHM

Added code for implemantation of 3D vision using realsense-ros and pcl packages.

2020-04-30 23:48 UTC, IquiBalamHM commented
@paulvazbad ¿Por qué no mejor muevo toda la carpeta point_cloud? En ella tengo dos paquetes principales, my_pcl_tutorial y realsense-ros.

2020-05-04 03:44 UTC, diegocardozo97 commented
Just remember that the package `realsense-ros` isn't going to be in our repository. Because, we are going to just install it in the computer and that's all, we don't need that code by itself.

2020-05-04 05:35 UTC, IquiBalamHM commented
You can't see whats inside the realsense-ros package but I modified a script of camera_description folder to do the processing of the pixels that I would receive from @SAlexisvf

2020-05-05 21:19 UTC, diegocardozo97 commented
Let's do this: rename the package _my_pcl_tutorial_ to _arm_vision_ and move it to be in `catkin_home/src/arm_vision`. Then, the files will become to be: `catkin_home/src/arm_vision/CMakeLists.txt`, `catkin_home/src/arm_vision/msg/SegmentedClustersArray.msg`, etc.

Also, let's not add _realsense-ros_ to the repository, delete the directory `catkin_home/src/point_cloud/realsense-ros/`, later if needed because, for example, you have changes in there, we add them.

2020-09-02 17:06 UTC, tomvik commented
@paulvazbad @IquiBalamHM I think we need to revive this PR

2020-09-12 22:54 UTC, tomvik commented
@paulvazbad @AuroTB please check this PR once more, I addressed the Cardozo's comment https://github.com/RoBorregos/Robocup-Home/pull/35#issuecomment-624312468

2020-09-13 17:52 UTC, paulvazbad requested changes
Looks good! Check out my comments and add this to your VScode installation please: https://docs.google.com/document/d/1SbFtM5Xw4Wr5yO_EQAByrgezefBusTbVpa3N82BmfrU/edit

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/move_base_msgs/.rosinstall
> +# IF YOU CHANGE IT, USE rosinstall FOR THE CHANGES TO TAKE EFFECT
Is this file supposed to be empty? Is it necessary then?

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/CMakeLists.txt
> +add_executable(example_node src/example1.cpp)
We should try to name `example1.cpp` something more useful

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/IncludersCloud.h
> +//#include <pcl/conversions.h>
Removed unused imports comments

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +
Remove extra space and comments after the import

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +pcl::PointXYZ Centroid;
Global variables should be avoided, if not possible at least make them const and put them inside a namespace:
https://docs.microsoft.com/en-us/cpp/cpp/namespaces-cpp?view=vs-2019#:~:text=%20Namespaces%20%28C%2B%2B%29%20%201%20using%20directives.%20The,implicit%20global...%204%20See%20also.%20%20More%20

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +}*/
Remove this commented code if not used.

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +    product += v1.z * v2.z;
why not a single line? (v1.x * v2.x) + (v1.y* v2.y) + (v1.z * v2.z)

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +    // Optional
Preferrable to leave a space before a comment.
`Code`

//Comment
`Code`

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +    dumb.z = cloud->points[inliers->indices[0]].z;
Is it possible to pass x,y,z as parameters to dumb in its instantiation? instead of assigning them afterwards

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +    dumb.z = cloud->points[inliers->indices[0]].z;
probably should name "dumb" something more descriptive

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +        // i++;
remove that comment

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/ProcessingCloud.h
> +        if (tempor <= 0) inliers2->indices.push_back(i);
call dotp directly inside the if() instead of creating tempor

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/package.xml
> +  <maintainer email="pev@todo.todo">pev</maintainer>
put your email here please and your GitHub username

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/package.xml
> +  <description>The arm_vision package</description>
a longer description if possible, I see you are using a 'PCL' library add some links and explanation of whats going on.

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +
rename example1.cpp to something more descriptive please

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +class segmentation {
segmentation -> Segmentation

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +class segmentation {
if possible put this class in a separate file Segmentation.h and Segmentation.cpp

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    ros::Publisher m_clusterPub;
members of class should have a _  before like: _m_nh;

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    // ... do data processing
unnecessary comment

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    // Perform the actual filtering
Space before comment

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    double zplanee = 0;
make const and caps lock `constexpr double ZPLANEE` at the beginning of the function

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    double tolerance = 0.05;
const

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +    float dumb[2] = {0.4, 0.03};
float dumb[2] rename to line_for_test.

2020-09-13 17:52 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/example1.cpp
> +
remove comment.

2020-09-15 02:49 UTC, tomvik commented
Done with the filename and with the empty message file.

Regarding the c++ style guide comments:

I understand and would address all of them, however I see this PR with the only purpose for @IquiBalamHM and I to start working on a shared package. As a next PR, I have planned to refactor the whole code, however I don't want to extend this one any further.

2020-09-15 03:27 UTC, paulvazbad commented
OK, then I will approve this as it is :) thank you @tomvik

2020-09-15 03:27 UTC, paulvazbad approved these changes

2020-09-15 15:13 UTC, merged