Arm vision kinect integration
RoBorregos/Robocup-Home pull request #87
Opened 2020-10-27 02:29 UTC by IquiBalamHM

Implemented a node where you can run it giving the camera as a parameter via rosrun.

2020-10-27 04:14 UTC, tomvik commented
As mentioned on the sprint planning, I'd like to see some automated testing for these modules. @IquiBalamHM let's work on that and once it is done, I'll review the code.

2020-10-27 18:12 UTC, paulvazbad requested changes

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.cpp
> +    if(camera_selection.compare("intel") == 0)
Define "intel" and "kinect" as static string constants, in case they need to be used somewhere else in the future.

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.cpp
> +
Maybe handle the case of something else connected,  throw an error

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.cpp
> +segmentation::segmentation(ros::NodeHandle nh, const std::string& camera_selection) : m_nh_(nh), camera_selection_(camera_selection) {
Class should be Segmentation with 'S' capitalized.

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.cpp
> +    sor.setLeafSize(0.01, 0.01, 0.01);
It is a good idea to keep constants defined somewhere else, to avoid ''magic numbers'

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.cpp
> +    double tolerance = 0.05;
const

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/include/SegmentationNode/SegmentationNode.h
> +class segmentation {
class Segmentation :)

2020-10-27 18:12 UTC, paulvazbad commented on catkin_home/src/arm_vision/src/cloud_segmentation_example.cpp
> +    }
Ah, here you handle the else case then, ok ignore the above comment.

2021-01-31 03:35 UTC, merged

2021-02-21 07:33 UTC, tomvik commented
Hi @Josecisneros001 and @IquiBalamHM: where are the automated tests?